### ISSUE TITLE
Windows App Certification Kit Test Fails in Debug configuration test

### ISSUE THREAD

**Issue by ranjittgs** [brianhama/ImageTools-WP81#2]
Hi,

We are unable to Pass Windows App Certification Kit test (WACK Test) for windows phone 8.1 application. 

It is producing below error in Debug configuration test,

The debug configuration test detected the following errors:
 1)The binary Phone.Controls.dll is built in debug mode.

Impact if not fixed:  Windows Phone Store doesn't allow a debug version of an app. 

How to fix:  Please make sure the app isn't linking to any debug versions of a framework and it is built with the release configuration.

I upgraded my project from windows phone 7.1 to windows phone 8.1.

Thanks and regards,
Ranjit.

**Comment by brianhama** [comment]
This is unrelated to this project.  Make sure to build in Release configuration.
